name: toyvalley
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  
  flutter_slidable: ^3.0.1
  
  #view
  cupertino_icons: ^1.0.8
  soundpool: ^2.4.1
  flutter_bloc: ^8.1.4
  crypto: ^3.0.3
  flutter_svg: ^2.0.10
  card_swiper: ^3.0.1
  gradient_borders: ^1.0.0 
  video_player: ^2.8.3
  page_transition: ^2.1.0
  android_intent_plus: ^4.0.3
  url_launcher: ^6.2.5
  lottie: ^3.1.0
  cached_network_image: ^3.3.1
  webview_flutter: ^4.11.0
  logging: ^1.2.0
  
  #logic
  get_it: ^7.6.7
  device_info_plus: ^9.1.2

  #rest
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1

  #storage
  flutter_secure_storage: ^9.0.0

  #config
  firebase_core: ^2.27.1
  firebase_messaging: ^14.7.20
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff" # for Android adaptive icons
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: VAG Rounded Std
      fonts:
        - asset: assets/fonts/VAG Rounded Std Bold.otf
